# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Build & Test

on:
  pull_request:
    branches: [ "master" ]
env:
  CONFIGURATION: Release
  WORKING_DIRECTORY: src\MobileApp

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        
    # Restore nugets
    - name: Restore
      run: dotnet restore

    # Build solution
    - name: Build
      run: dotnet build --no-restore
    
    # Execute TEST
    - name: Test
      run: dotnet test --no-build --verbosity normal
